_sink:
  _target_: matrix.agents.p2p_agents.Sink
  debug: ${debug}
  dead_orchestrator_tracking: ${dead_orchestrator_tracking}
  max_concurrent_tasks: ${max_concurrent_tasks}
  
  ray_resources:
    num_cpus: 2
    # resources:
    #   qos-data_high: 0.001
